CMake: Fix incomplete 'is macOS?' checks
A user might configure Qt with

`-DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_SYSTEM_NAME=Darwin
-DCMAKE_CROSSCOMPILING=ON`

to cross-compile an intel x64 macOS Qt on an arm64 macOS host.

Some of the code only checks `NOT CMAKE_SYSTEM_NAME` to determine if
we're building for macOS. In one case this results in skipping
setting the minimum deployment target.

This causes a build failure about trying to use deprecated API:

  error: 'CGDisplayCreateImageForRect' is unavailable:
  obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.

Make sure to explicitly also check for
  `CMAKE_SYSTEM_NAME STREQUAL "Darwin"`
in these cases.

Adjust a few more code paths with the same issue.

Pick-to: 6.10 6.8
Change-Id: Ifadfadee5d3f9d13fe5966ad4809b029ebb67d80
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>
(cherry picked from commit 9fa80de317d57fd830af86be057da09a0a06e9b8)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>