Fix QReadWriteLock build error with TSAN
qreadwritelock.h:136:34: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]

QBasicReadWriteLock::describeLockInternal(void *dd)
was called with a `d` being const.

But the only caller of describeLockForTSan has a non-const d,
so no need for the const in the signature of describeLockInternal.

Amends a6b062931dca498adb0518481d1c57d2d4322143

Pick-to: 6.12
Change-Id: I97733d791d96b11357b7c18a06cf0e494571b0d7
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>