Fix signed-unsigned mismatch with gcc 4.9.0
Android NDK r10d with gcc 4.9.0 fails with:

gglobal/qoperatingsystemversion.cpp: In static member function 'static QOperatingSystemVersion QOperatingSystemVersion::current()':
global/qoperatingsystemversion.cpp:150:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (sdk >= 1 && sdk <= sizeof(versions) / sizeof(versions[0])) {

Switch to size_t and store the array index in order to simplify.

Code is new in dev, introduced in 26b2ad5a181eab7ad04ba819004bcc619c24147b

Change-Id: Ia19cfcb9789e225760f4d1a05c91463f4c7c2302
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>