Fix FTBFS with -qtnamespace
qtbase/src/corelib/kernel/qvariant.h(54): error C2888:
'const bool qIsRelocatable<qt::QVariant>': symbol cannot be defined within namespace 'qt'

Amends 0ca803a5d325f26f5e4e0fcab8b9c9a02f154336

Fixes: QTBUG-112016
Change-Id: I43b3f292fa85b6cda00f36da6c8aff65da4ed742
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit c0a732f984f407f7613805ff04b8a6d46c12f754)