QJsonParseError: fix clang -Wshorten-64-to-32 warnings
Change it to qint64 in Qt7, as requested in code review, so as to make
it easier to extend it in the future.

Pick-to: 6.8 6.5
Change-Id: If893d719dd0457fac46fdd37ff95ce95222b1858
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit ca725e1465fcc6d71b25c414aa9a0f0c3faad1d5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>