QtNetwork: Remove duplicated QT_DECL_METATYPE
It causes conflicts in CMake Unity (Jumbo) builds:

qnetworkreplyimpl_p.h:161:1: error: specialization of QMetaTypeId<QSharedPointer<char> >after instantiation
  161 | QT_DECL_METATYPE_EXTERN_TAGGED(QSharedPointer<char>, QSharedPointer_char, Q_NETWORK_EXPORT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
qtbase/src/network/access/qnetworkreplyimpl_p.h:161:1: error: redefinition of struct QMetaTypeId<QSharedPointer<char> >
qtbase/src/corelib/kernel/qmetatype.h:1711:1: note: previous definition of struct QMetaTypeId<QSharedPointer<char> >
 1711 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(Q_DECLARE_METATYPE_TEMPLATE_SMART_POINTER_ITER)

Task-number: QTBUG-109394
Change-Id: I91d13a99dd0f5602ba8d4d8f3baf7659cf63aeef
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit f4e212b9c430c7300e07ec896116f090cf2d8610)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>