QEventLoopLocker: fix signed/unsigned mismatch in move constructor
  C:\xxx\MSVC\14.51.36231\include\utility(831): error C4365: '=':
  conversion from 'int' to '_Ty', signed/unsigned mismatch
          with
          [
              _Ty=quintptr
          ]
  C:\xxx\MSVC\14.51.36231\include\utility(831): note: the template
  instantiation context (the oldest one first) is
  C:\xxx\include\QtCore/qeventloop.h(68): note: see reference to
  function template instantiation '_Ty std::exchange<quintptr,int>(_Ty
  &,_Other &&) noexcept' being compiled
          with
          [
              _Ty=quintptr,
              _Other=int
          ]

Amends c2956f8f7685b624d7693ff644125d0f594c585d (6.7)

Pick-to: 6.11 6.8
Change-Id: Id63bc5f1827e2fe16e03656ba89c9dcfaa4ff1d7
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit f4cb9654f1c2b231f3308c338dce7f0a2a173a90)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>