Fix GCC 4.9 warning about repeated attributes
qxcbscreen.cpp:701:21: error: ‘QDebug operator<<(QDebug, const
QXcbScreen*)’: visibility attribute ignored because it
qxcbscreen.h:149:21: error: conflicts with previous declaration here [-
Werror=attributes]

Change-Id: Ia0aac2f09e9245339951ffff13c77c23cb9430c5
Reviewed-by: Uli Schlachter <psychon@znc.in>
Reviewed-by: Shawn Rutledge <shawn.rutledge@theqtcompany.com>