Avoid unused parameter 'grab' warnings
Android (5220042 based on r346389c) clang version 8.0.7:

src/plugins/platforms/android/qandroidplatformwindow.h:68:35: error: unused parameter 'grab' [-Werror,-Wunused-parameter]
    bool setMouseGrabEnabled(bool grab) override { return false; }
                                  ^
src/plugins/platforms/android/qandroidplatformwindow.h:69:38: error: unused parameter 'grab' [-Werror,-Wunused-parameter]
    bool setKeyboardGrabEnabled(bool grab) override { return false; }
                                     ^

Change-Id: I4d8a18d5e3bfbc13c05b47f0cdfe10370673e359
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>