xcb: fix build with libc++ from LLVM 21 - std::free() not defined
Amends commit d67214302f269242ae3d8d2b962fd91ec42c979e, which added
these macros and std::unique_ptr use, deleting with std::free(). But
since the memory was allocated by a C library (libxcb and friends),
strictly speaking we ought to free with free(), not std::free(). In that
case, the deleter is the same as QScopedPointerPodDeleter.

qxcbconnection_basic.h:127:54: error: no member named 'free' in namespace 'std'; did you mean simply 'free'?

Fixes: QTBUG-144700
Pick-to: 6.10 6.8
Change-Id: I19ce1e43986c1e10d2a5fffd807ddcf990334609
Reviewed-by: Giuseppe D'Angelo <giuseppe.dangelo@kdab.com>
(cherry picked from commit d857f069e5db614b457464bd6153f0f6e562d155)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 3cce053fbf8b5d5eba2bb68ec9997ef0ddd7a21b)