Fix build with MSVC2022 17.14.19
When building it errors out with:
C:/gitlab/qt/qtbase/src/gui/text/qcssparser.cpp(121): error C2872: 'Font': ambiguous symbol
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\comdef.h(489): note: could be 'Font'

Because comdef.h has a Font class.

Fixes: QTBUG-141755
Fixes: QTBUG-146146
Pick-to: 6.12 6.11 6.8
Change-Id: I7d86ee8bd367c120cf32d5c8142a2aaebef347cd
Reviewed-by: Marc Mutz <marc.mutz@qt.io>