XCB: Don't override non-existent method when QT_NO_OPENGL
QBackingStore only has a toImage() method if OpenGL is enabled. I
noticed this because compilation failed for me, thanks to
Q_DECL_OVERRIDE.

qxcbbackingstore.h:60:12: error: ‘QImage QXcbBackingStore::toImage() const’ marked override, but does not override
     QImage toImage() const Q_DECL_OVERRIDE;

Change-Id: I6b45ef41c53d819d81fe657f26adc1f630fec6bb
Reviewed-by: Jørgen Lind <jorgen.lind@theqtcompany.com>