QDBusError: remove the unused, unusable "unused" member in Qt 7
"Amends" commit 258e4d05edcb36406c32be56a8207fe992d284dc, which marked
this member for removal in Qt 6. Which we didn't do.

Pick-to: 6.12
Change-Id: I2e5cc0ec738559f518ecfffd3aea1bfcd70bcac8
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>
Reviewed-by: Marc Mutz <marc.mutz@qt.io>