Fix multiple definition linker error for ensurePositionTopLeft
Including qtesthelpers_p.h across multiple translation units within
the same static library target (e.g. QuickControlsTestUtilsPrivate)
resulted in duplicate symbol definitions for ensurePositionTopLeft.

Fix this by marking the function definition as static inline,
matching the pattern used by the other utility functions in
the same header file.

The error was:

/home/mitch/dev/qt-dev2/qtbase/src/testlib/qtesthelpers_p.h:97: multiple definition of `QTestPrivate::ensurePositionTopLeft(QWindow*)'; /home/mitch/dev/qt-dev2-debug/qtbase/lib/libQt6QuickControlsTestUtils.a(quickcontrolstestutilsprivate_qmltyperegistrations.cpp.o):
/home/mitch/dev/qt-dev2/qtbase/src/testlib/qtesthelpers_p.h:97: first defined here

Amends 7929852c1d39e12b7c586b5c6d257c9df27c01df.

Pick-to: 6.11
Change-Id: Ief2f76f4e32d0f8b048a219570db63b6bc1a99ad
Reviewed-by: Frederic Lefebvre <frederic.lefebvre@qt.io>
Reviewed-by: Axel Spoerl <axel.spoerl@qt.io>
(cherry picked from commit d618c6a86a2b402ca1806e205b4183ce743fc7eb)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>