Fix some issues of a clang-cl developer build
- qeasingcurve.cpp: Add a cast, fixing:
  qeasingcurve.cpp(1515,25): error: implicit conversion between pointer-to-function and pointer-to-object is a Microsoft extension [-Werror,-Wmicrosoft-cast]
- Disable copy and move of QMainWindowLayoutSeparatorHelper, fixing:
  qbasictimer.h(59,5): note: 'QBasicTimer' has been explicitly marked deprecated here
    QT_DEPRECATED_X("copy-construction is unsupported; use move-construction instead")

Task-number: QTBUG-63512
Change-Id: I4d12a29cb1dcd68da9f9316c9e42992f218e6045
Reviewed-by: Oliver Wolff <oliver.wolff@qt.io>
Reviewed-by: André de la Rocha <andre.rocha@qt.io>
Reviewed-by: Shawn Rutledge <shawn.rutledge@qt.io>