moc: fix warning about implicit conversion changing signedness
Amends commit 637ccf5332010b2b6480697993a779457702fd70, which added the
hash information.

error: implicit conversion changes signedness: 'uint' (aka 'unsigned int') to 'int' [-Werror,-Wsign-conversion]

Fixes: QTBUG-143352
Change-Id: I5ee7434fcd4928928ad8fffda454160073825af7
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Olivier De Cannière <olivier.decanniere@qt.io>
(cherry picked from commit 8c08d182eca8b76cfb7e4dd9a5621c4283bf2aef)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>