Fix rgb64 on aarch64
Instead of quint64 use uint64_t in order to avoid errors like

error: invalid conversion from 'quint64* {aka long long unsigned int*}' to
'const uint64_t* {aka const long unsigned int*}'

Unify const usage for LOAD and switch to C++ casts.

Change-Id: I4a6a8ec5b24f2f306645178fe00f6bfb1c429403
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>