iOS: Make default build static again (take 2)
amends aa3d08ee868c281e38ad1a476f6f3becb4c9aa34, which attempted to
revert the default change to -shared in 4c26b4863361 but failed to take
into account an explicitly passed -shared argument, resulting in:

ERROR: Feature 'shared' was enabled, but the pre-condition
'!config.uikit && !config.integrity' failed.

Change-Id: Ide381624245e7c132a07e98c9107be7126dd488a
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@qt.io>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@qt.io>
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>