Remove SSL includes from qhttpnetworkconnection_p.h
On Windows, qsslcontext_openssl_p.h pulls in an unsanitized
windows.h, causing the infamous min/max macros to be defined,
requiring a #define NOMINMAX in qhttp2protocolhandler.cpp.

This in turn breaks the MinGW developer build since that has
NOMINMAX globally defined:

access\qhttp2protocolhandler.cpp:40:0: error: "NOMINMAX" redefined [-Werror]

Remove the include, adding missing forward declarations and include
directives to the source files.

Change-Id: Ic1c2c711d87599b15ad6e2d87eae7153a44ace47
Reviewed-by: Timur Pocheptsov <timur.pocheptsov@theqtcompany.com>