Fix build without abstractslider
qtbase/src/widgets/styles/qcommonstyle_p.h:102:53: error: field ‘animations’ has incomplete type ‘QHash<const QObject*, QStyleAnimation*>’
  102 |     mutable QHash<const QObject*, QStyleAnimation*> animations;
      |                                                     ^~~~~~~~~~

Change-Id: Ib7b4a5031c1447248f4db1f4ea6629a31d610bcb
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 86d8d67146e20ac9d342a9d8c6901b35c899427e)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>