ohos: fix build with llvm/clang 22 about missing initializer
One of the errors is like:

src/plugins/platforms/ohos/render/qohossurface.cpp:90:9: error: missing field 'revents' initializer [-Werror,-Wmissing-designated-field-initializers]
   90 |         },
      |         ^

Pick-to: 6.12
Change-Id: I353dcf757e7335e2b5847aca97ec170088406759
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>