DeviceHandlerList: work around GCC 16 false-positive warning
The contents of a QArrayDataPointer such as QString are never
uninitialized, so this can only be a false positive. It wouldn't be the
first time GCC produces warnings with GCC's own Standard Library classes
either.

Fortunately, the work around is trivial: pass by value and use
std::move. And as a benefit, I can use emplace_back and make the
implementation better.

In member function ‘QArrayDataPointer<char16_t>::confirmState() const’,
    inlined from ‘QArrayDataPointer<char16_t>::QArrayDataPointer(QTypedArrayData<char16_t>*, char16_t*, long long)’ at qarraydatapointer.h:60:21,
    inlined from ‘QArrayDataPointer<char16_t>::QArrayDataPointer(QArrayDataPointer<char16_t> const&)’ at qarraydatapointer.h:46:59,
    inlined from ‘QString::QString(QString const&)’ at qstring.h:259:68,
    inlined from ‘QtInputSupport::DeviceHandlerList<QEvdevKeyboardHandler>::add(QString const&, std::unique_ptr<QEvdevKeyboardHandler, std::default_delete<QEvdevKeyboardHandler> >)’ at devicehandlerlist_p.h:36:20,
    inlined from ‘QEvdevKeyboardManager::addKeyboard(QString const&)’ at qevdevkeyboardmanager.cpp:62:24:
qassert.h:113:38: error: ‘SR.525’ may be used uninitialized [-Werror=maybe-uninitialized]
devicehandlerlist_p.h:36:20: note: ‘SR.525’ was declared here
   36 |         v.push_back({deviceNode, std::move(handler)});
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Pick-to: 6.8
Change-Id: Ie1ff728e85358effa058fffd1700000b4a9bd0b1
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 2be39d2fa91aa06df766873aa63458be5923290e)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>