QSharedDataPointer: Use new comparison helper macros
Provide the new comparesEqual() helper function as an implementation of
the (in)equality operators and compareThreeWay() helper function for
the rest of the relational operators.
Use Q_DECLARE_STRONGLY_ORDERED to provide all relational operators.

Use the new Qt::totally_ordered_wrapper to wrap the "d" pointer to
avoid UB when performing comparisons of QSharedDataPointer.

The old implementation of the operators between QSharedDataPointer
and the normal pointer T* used to cause a bug but this was not noticed
because QSharedDataPointer didn't have any tests.
I added tests and tried to compare using operator<(). I got
build issues:
       error: no match for call to
       ‘(std::less<MyClass*>) (const MyClass*&, MyClass* const&)’
This happens because QSharedDataPointer has an implicit conversion
to MyClass*.
Making the normal pointer T* non-const as follow resolves the issue:
 DECLARE_COMPARE_SET(const QSharedDataPointer &p1, p1.d, T *ptr, ptr)
 DECLARE_COMPARE_SET(T *ptr, ptr, const QSharedDataPointer &p2, p2.d)

A similar bug happens if we make the normal pointer const in the
comparison macro Q_DECLARE_STRONGLY_ORDERED. The relational operators
will be ambiguous. The compiler picks between
operator<(QSharedDataPointer<MyClass>, MyClass*) and
opeartor<(MyClass*, MyClass*) (In case we're calling <).
Therefore, use:
   Q_DECLARE_STRONGLY_ORDERED(QSharedDataPointer, T*)

Add some comparisons related tests for QSharedDataPointer.
Use QT_TEST_ALL_COMPARISON_OPS macros in unit-tests.

Task-number: QTBUG-120306
Change-Id: I8d1159a01651bab442b79a89c53e064914103133
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>