QGlobalStatic: fix Clang warning about expression in unevaluated context
From Clang 13:

qlocale.cpp:854:161: error: expression with side effects has no effect in an unevaluated context [-Werror,-Wunevaluated-expression]

Change-Id: Ibf4acec0f166495998f7fffd16d6c75ef1e04262
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 77e4177d1634ed8e1d7eed32bdd8e9967ae6e2fe)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>