QXcbNativeInterface: remove unused field m_sysTraySelectionAtom
Says Clang:

qxcbnativeinterface.h:141:16: error: private field 'm_sysTraySelectionAtom' is not used [-Werror,-Wunused-private-field]
    xcb_atom_t m_sysTraySelectionAtom = XCB_ATOM_NONE;
               ^
Detected by includemocs.

Change-Id: Ie08c2b268b508ed87e63010fc22311ab6c8d0e40
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
(cherry picked from commit 1fa72be23061f3aaab3ef1b6acc7e742b045bed6)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>