Remove size assert in QMultiHash::take()
It doesn't exist in every instantiation of the template; this becomes
evident when attempting to build QQuickListView:

error: 'using Chain = struct QHashPrivate::MultiNodeChain<FxViewItem*>'
  {aka 'struct QHashPrivate::MultiNodeChain<FxViewItem*>'} has no member named 'size'

Change-Id: I24748c15f3995083eec06d86a3c0dced2209c303
Reviewed-by: Lars Knoll <lars.knoll@qt.io>