Fix a build issue
- If configure Qt with the following command:
cmake ../qt5/ -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_BUILD_EXAMPLES=ON -DQT_BUILD_TESTS=ON

I observe the following issue on building:
qtbase/tests/auto/corelib/kernel/qvariant/relocatable_change.h:11:10: fatal error: QTest: No such file or directory
   11 | #include <QTest>
      |          ^~~~~~~

Change-Id: If01c39456a820b14e7a698bd91ef9c5baabbe978
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>
(cherry picked from commit 6c1a003dbd8b211fefd18b84842d7ffab701ca24)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 3ffbfc32457ad788d9ebad23e42483c3e4d38368)