Windows QPA: Fix compilation with MinGW 7.1
MinGW 7.1 claims the qUuidOf<> specializations are unused:

In file included from accessible\qwindowsaccessibility.cpp:59:0:
accessible\iaccessible2.h:274:5: error: 'IID qUuidOf() [with DesiredInterface = IAccessible2]' defined but not used [-Werror=unused-function]
 IID qUuidOf<IAccessible2>() { return IID_IAccessible2; }
     ^~~~~~~~~~~~~~~~~~~~~
In file included from accessible\qwindowsaccessibility.cpp:59:0:
accessible\iaccessible2.h:58:5: error: 'IID qUuidOf() [with DesiredInterface = IAccessibleComponent]' defined but not used [-Werror=unused-function]
 IID qUuidOf<IAccessibleComponent>() { return IID_IAccessibleComponent; }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amends 4f599c5ea180f5246adf2a95c158b50f027a8c21.

Change-Id: Iafcfe8b8d8ca9cdf00663f39ad491347b51d3ace
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@qt.io>