rhi: vulkan: Fix incorrect self-dependency with multiview
Running the qrhi autotest shows Vulkan validation errors when multiview
is involved. This was not the case before 6.11.

tst_QRhi::renderPassDescriptorCompatibility(Vulkan) vkDebug: Validation
Error: [ VUID-VkRenderPassCreateInfo2-pDependencies-03060 ] | MessageID
= 0xb07eead1 | vkCreateRenderPass2KHR(): pDependencies[0] specifies a
self-dependency for subpass 0 with a viewMask 0x3, but does not specify
VK_DEPENDENCY_VIEW_LOCAL_BIT. The Vulkan spec states: For any element of
pDependencies where its srcSubpass member equals its dstSubpass member,
if the viewMask member of the corresponding element of pSubpasses
includes more than one bit, its dependencyFlags member must include
VK_DEPENDENCY_VIEW_LOCAL_BIT

Avoid this by adding VK_DEPENDENCY_VIEW_LOCAL_BIT conditionally.

Amends 25e79d1526bae615f84a3976733fd0fdf71bd67d

Fixes: QTBUG-143587
Change-Id: I97490eb223a183b9610bc1dce33f28ed4b919759
Reviewed-by: Antti Määttä <antti.maatta@qt.io>
(cherry picked from commit f8950350893c130089f29e9f829943a33e7b0d94)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>