QFlatMap: Fix compiler error regarding unused lambda capture
When compiling Qt Multimedia for Android Arm64, using Android NDK
27.2.12479018, Clang 18.0.3, we get the following compiler error:

error: lambda capture 'this' is not used [-Werror, -Wunused-lambda-captu
re] 1027 | auto equivalent = [this](const auto &lhs, const auto &rhs) {

This patch makes the lambda use 'this->' qualification explicitly, using
a different name to avoid the special 'this' capture semantics, and
solves the compiler warning.

Pick-to: 6.11 6.8
Change-Id: I53da12c3a6a381338b48c9f05f90df4ee4e40ac0
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>