macdeployqt: Fix deploying libraries with `reexport`
Fixes deploying libgcc, currently it fails to change the rpaths with the
following error:

ERROR: Could not parse otool output line:
"\t/usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib
(compatibility version 1.0.0, current version 1.1.0, reexport)"

Change-Id: I5c866a375f88e3b222cbdbebc167b04174f753b2
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>
(cherry picked from commit 2e8c84cda25de38d64669a9d078d87c7d2bf451c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>