Fix build with GCC 13: target specific option mismatch
range_access.h:274:5: error: inlining failed in call to ‘always_inline’
‘constexpr std::size_t std::size(const _Tp (&)[_Nm]) noexcept [with _Tp
= short unsigned int; long unsigned int _Nm = 34]’: target specific
option mismatch

qsimd.cpp:367:35: note: called from here

Change-Id: Ide4dbd0777a44ed0870efffd1739097c71991822
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit d298ec3a6f4634254c6685398d49b1ba4dfa8e6b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>