QAnyStringView: remove direct #include <compare>
Since commit 2bc9ad0e5dd75cf69f4a8bf94a6a917de2b4e8c4, we have our
qcompare.h header, which takes care of this. This also fixes the build
when the compiler supports operator<=> but the Standard Library doesn't
(e.g, VxWorks):

qanystringview.h:13:10: fatal error: 'compare' file not found

Change-Id: I8a96935cf6c742259c9dfffd17e9014a52d4991c
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>
(cherry picked from commit f48f425d3ebc76b242243b440fb853ba29e0970c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>