Windows: Fix qAbort() definition for MSVC with unity build
src\corelib\global\qglobal_p.h(57): error C2381: 'qAbort': redefinition; 'noreturn' differs
src/corelib/global/qassert.cpp(24): note: see declaration of 'qAbort'

The error started after 1ef5f50e, when unity build source files changed.

Change-Id: Id90ee20976423b9ae6ec691ee15602256f7c1fe9
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 23877db5639deca70dc8cc1a7299b2cee629c7d8)
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>