Tests: fix namespaced build on Windows
Amends 371214dea7f92b3170d0239b3d9944275adf951a.

tst_qfile.cpp:401:9: error: reference to ‘QTest’ is ambiguous
qttestglobal.h:27:11: note: candidates are: ‘namespace TestNamespace::QTest { }
filesystem.h:28:11: note:                 ‘namespace QTest { }’

Change-Id: I07ec23f3cb174fb197c3fffd17215c1eeeadf7fd
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit d18d34134115d003808a7284c095bed694ebf685)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>