Add missing #includes
This is needed by static analysis tools (which compile each header on
its own, IIUC), e.g. clang-tidy:
src/widgets/itemviews/qtableview_p.h:99:22: error: unknown type name
'QTableView' [clang-diagnostic-error].
    Q_DECLARE_PUBLIC(QTableView)
                     ^

Change-Id: I84a1221469e9a78f243cc892ef7c60da9b515718
Reviewed-by: Richard Moe Gustavsen <richard.gustavsen@qt.io>