QColor: clean up qcolor_p.h
Only qt_get_hex_rgb(const char*, QRgb*) is used outside qcolor.cpp
(in qxpmhandler.cpp), so remove all other function declarations from
qcolor_p.h, and make the functions file-static in qcolor.cpp, removing
their qt_ prefix to avoid confusion.

Exception: it turned out that qt_get_named_rgb(const char *, QRgb*)
wasn't actually used anywhere, but a follow-up commit will fix this.
Adjust interface to that of the QChar overload (add explicit int len).

Simplify conditional compilation of QT_NO_COLORNAMES: move the ifdef
inside get_colornames, to avoid duplicating the declaration, and
remove the empty implementation of get_named_rgb, since their use is
already conditional on QT_NO_COLORNAMES not being defined.

Change-Id: Iaf685dfbea0b9d3bd010448dac0e95be7b097ce5
Reviewed-by: Edward Welbourne <edward.welbourne@qt.io>