wasm: exit with clear error on suspend without asyncify
This currently exits with a rather obscure error like

   Uncaught (in promise) TypeError: resume is not a function

Add a qFatal() with an error message explaining what went
wrong and with a pointer to the documentation on how to fix it.

Change-Id: I1529a23a01c8c0344101a9869261d0138f2248d0
Reviewed-by: Lorn Potter <lorn.potter@qt.io>
(cherry picked from commit 510df2974d1998c631203281a3734d13bd8ec710)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>