Fix warning caused by warning fix
qevent.h:865:36: error: unknown warning group '-Wunused-private-field', ignored [-Werror,-Wunknown-pragmas]

Instead, just use Q_UNUSED() like I've done for the other unused
members.

Change-Id: I3adeb06937cee8b8ac24a1d5081be03931ac98b7
Reviewed-by: Stephen Kelly <stephen.kelly@kdab.com>