Fix warnings about unused functions
The operator<= and operator>= overloads for QPoint are used only with
Q_ASSERT. Clang was correct that they are not used.

Even though they are inline, Clang reports the functions as unused
because they were inside an anonymous namespace. So take the off the
namespace. They are correct for external use, should they be exported
by accident (which they aren't now).

painting/qpathsimplifier.cpp:76:13: error: unused function 'operator<='
      [-Werror,-Wunused-function]
inline bool operator <= (const QPoint &a, const QPoint &b)

Change-Id: I67415621e777fd0d59cbdede26c34d8bb13f7346
Reviewed-by: Gunnar Sletta <gunnar.sletta@digia.com>