Remove unused variable
This fixes clang a clang warning:
src/plugins/platforms/kms/qkmsscreen.h:114:18: error: private field
'm_refreshTime' is not used [-Werror,-Wunused-private-field]
    unsigned int m_refreshTime;
                     ^
                     1 error generated.

Change-Id: I850f676abbde595963373afaf630307042dbf5a7
Reviewed-by: Andy Nichols <andy.nichols@digia.com>