QDBusError: remove the unused, unusable "unused" member in Qt 7
"Amends" commit 258e4d05edcb36406c32be56a8207fe992d284dc, which marked
this member for removal in Qt 6. Which we didn't do.

Change-Id: I2e5cc0ec738559f518ecfffd3aea1bfcd70bcac8
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 971a4b27bc44d236396d8ff4f8bbc5a2d3609e46)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>