ohos: fix build with llvm/clang 22 about missing initializer
One of the errors is like:

src/plugins/platforms/ohos/render/qohossurface.cpp:90:9: error: missing field 'revents' initializer [-Werror,-Wmissing-designated-field-initializers]
   90 |         },
      |         ^

Change-Id: I353dcf757e7335e2b5847aca97ec170088406759
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>
(cherry picked from commit b9da9b47fac416e195b1f0760f7cc63813d1c0ff)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>