harmonyostestrunner: Fix unity build
Move conflicting timeout constants into the functions, fixing:

In file included from qtbase/src/tools/harmonyostestrunner/CMakeFiles/harmonyostestrunner.dir
/Unity/unity_0_cxx.cxx:13:
qtbase/src/tools/harmonyostestrunner/shellhelpers.cpp:10:22: error: redefinition of 'constexpr const int startTimeoutMs'
In file included from qtbase/src/tools/harmonyostestrunner/CMakeFiles/harmonyostestrunner.dir
/Unity/unity_0_cxx.cxx:10:
qtbase/src/tools/harmonyostestrunner/hdc.cpp:14:22: note: 'constexpr const int startTimeoutMs' previously defined here

Task-number: QTBUG-109394
Change-Id: I50f818870a278bb86140292989d0f8969d8d8a30
Reviewed-by: Liang Qi <liang.qi@qt.io>
Reviewed-by: Dawid Śliwa <dawid.sliwa@qt.io>
(cherry picked from commit 5862508c27a13a2e0809728bb45db48262ecb8ea)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>