QToolbar: Un-hide the QLayout::indexOf non-virtual
Breaks the build with QT6_VIRTUAL

qtoolbarlayout_p.h:99:9: error: 'QToolBarLayout::indexOf' hides overloaded virtual function [-Werror,-Woverloaded-virtual]

Change-Id: I6efb28c3145047559ec0fffd15386c39739b42f9
Reviewed-by: David Faure <david.faure@kdab.com>