iOS: Don't mark int main as extern "C"
When compiling Qt for iOS using iOS SDK 26.4 the compiler warns:

/Users/nils/qtdev/dev/src/qtbase/src/plugins/platforms/ios/qioseventdisp
atcher.mm:274:16: error: 'main' should not be 'extern "C"' [-Werror,-Wma
in]
  274 | extern "C" int main(int argc, char *argv[]);

This patch removes extern "C" from this function declaration.

Our main-wrapper log still works, as main is implicitly mangled
as a C symbol.

Change-Id: I8dbc3b0f6ec5e1b06e7e1eed1b414c0c864feea8
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>
(cherry picked from commit 3143f96bf50b26caa91f55839345496a2e7d2bac)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>