Android: Use default priority for OnBackInvokedDispatcher
Currently, when running Qt Android application on devices that run API
Level 35, the app crashes on startup with an uncaught exception:

java.lang.IllegalArgumentException: Application registered OnBackInvoked
Callback cannot have negative priority. Priority: -2.

The function guards against devices with API level > 33, but the
constant OnBackInvokedDispatcher.PRIORITY_SYSTEM_NAVIGATION_OBSERVER
was introduced in API level 36. Prior to this, priority must not be
negative.

This patch changes it to use the default priority.

Task-number: QTBUG-143558
Change-Id: Ifa4836d20b1bed418ede47c3a7218e18466082e1
Reviewed-by: Assam Boudjelthia <assam.boudjelthia@qt.io>