Restore binary compatibility with pre-5.6 qt_handleMouseEvent
An internal, private symbol was changed in
beef975f92e42143c464d68afa6b8cd4f7ef7389. However, this symbol was being
used by some inline functions in QtTest, and this therefore introduced a
BIC. This change simple adds back a symbol with the original signature.

I recall seeing this in my own work, and the KDE CI system hits this as
well:

  libKF5KDELibs4Support.so.5.25.0: undefined reference to
  `qt_handleMouseEvent(QWindow*, QPointF const&, QPointF const&,
  QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>)'

Task-number: QTBUG-52205
Change-Id: I4e85996850cc436b6a31addca3a8f9829c0c5edd
(cherry picked from commit 7f12f94e481d4908ee7b68e2cab8263b7476b054)
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>