Fix qdoc errors in QIcon header
Add missing forward declaration, fixing:

src/gui/image/qicon.h:93:16: error: unknown type name 'QPainter'

This apparently only happens for qdoc.

Change-Id: I39e78258f16628d477b629778241c4f5031820c4
Reviewed-by: Paul Wicking <paul.wicking@qt.io>