Remove ; after QT_DECLARE_EXTERN_RESOURCE
This avoids a warning with clang compiler.

error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
QT_DECLARE_EXTERN_RESOURCE(AusweisAppQmlModuleMoreView_raw_qml_0);

Change-Id: Id289080884ba2b017e884a15debfdd46102f1093
Reviewed-by:  Alexey Edelev <alexey.edelev@qt.io>
(cherry picked from commit 11259972a3c5d1918f889f145a1f223bf7d876a8)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>