Clang 10: Fix missing-exception-spec error on Windows
Fix error

qtbase/src/plugins/platforms/windows/qwindowsdropdataobject.cpp:67:25: error: 'GetData' is missing exception specification '__attribute__((nothrow))' [-Werror,-Wmissing-exception-spec]
QWindowsDropDataObject::GetData(LPFORMATETC pformatetc, LPSTGMEDIUM pmedium)

Follow the example of just disabling microsoft-exception-spec  here.

Change-Id: I61feb59e188bff7fdfb30e88f8a06c61ec808828
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>