QSqlError: misc cleanup
- fix formatting for qsqlerror.cpp/.h
- replace a size() == 1 "x"_L1 with u'x'

Change-Id: I74c92f27be4345737fcfc73368f834a2f7920808
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit b5fe88a6e5251251d0f65b2f9cb5b28c01cc3b63)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>