Remove some dead code from qtriangulator.cpp
The CompareEdges functor class is never used anywhere. Clang saw it
through to the static function that never got used:

qtriangulator.cpp:227:12: error: unused function 'comparePoints'
      [-Werror,-Wunused-function]
static int comparePoints(const QPodPoint &u, const QPodPoint &v)
           ^

Change-Id: I67d821e454daf82bd8107bf20f787aff9496e878
Reviewed-by: Samuel Rødal <samuel.rodal@digia.com>