qHash: fix compilation of SipHash64 on 32-bit: shift >= 32
Amends aadf1d447cd07a961539c6ab607ca65c3297622a because size_t on 32-bit
platforms is 32-bit.

qhash.cpp:331:15: error: left shift count >= width of type [-Werror=shift-count-overflow]

Change-Id: I5f663c2f9f4149af84fefffd17c0567b17f832ce
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>