QNativeSocketEngine: fix build with FreeBSD: sockaddr_dl wasn't declared
This partially reverts fcb548878bfae3db34d482f3ad97074aca76b410.

qnativesocketengine_unix.cpp:872:40: error: unknown type name
'sockaddr_dl'; did you mean 'sockaddr_in'?

Change-Id: Ifeb6206a9fa04424964bfffd178844096ee7741b
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>
(cherry picked from commit e95467bc6b685deccc0c3c8dfa337317a6b44eb0)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>