QDnsLookup/Windows: add missing typedefs for older mingw
Amend 9a73bc5f3d48f6ccaef02871ad62284dd61eff38 with more typedefs
missing from older mingw headers:

| src/network/kernel/qdnslookup_win.cpp:40:3: error: 'PDNS_QUERY_COMPLETION_ROUTINE' does not name a type; did you mean 'LPOVERLAPPED_COMPLETION_ROUTINE'?
|    40 |   PDNS_QUERY_COMPLETION_ROUTINE pQueryCompletionCallback;
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| src/network/kernel/qdnslookup_win.cpp:47:9: error: 'PDNS_QUERY_RESULT' has not been declared
|    47 |         PDNS_QUERY_RESULT   pQueryResults,
|       |         ^~~~~~~~~~~~~~~~~
| src/network/kernel/qdnslookup_win.cpp:77:5: error: 'DNS_QUERY_RESULT' was not declared in this scope; did you mean 'DNS_QUERY_REQUEST'?
|    77 |     DNS_QUERY_RESULT results = {};
|       |     ^~~~~~~~~~~~~~~~

Change-Id: I812525aaa938764d337923820d0eb8b3e24a0004
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>