Fix Clang 10 warning about misleading indentation
qcombobox.cpp:3282:13: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]

Change-Id: I99ab0f318b1c43b89888fffd160b5a7310c0a0d0
Reviewed-by: Giuseppe D'Angelo <giuseppe.dangelo@kdab.com>
(cherry picked from commit ee3ab7829d0e56feb307e1dff7935d231dfade3a)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>