QIODevice: fix converting OpenMode flag in debug output
Suppress error:

src\corelib\io\qiodevice.cpp(791): error C2440:
 '<function-style-cast>': cannot convert from 'QIODeviceBase::OpenMode'
  to 'quint32'

Pick-to: 6.1 6.2
Change-Id: I6b6e94790942d3af62bc2f38afad97c0b3c80817
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@gmx.de>