qpixellayout.cpp: mark some specializations of fetchPixel as unused
Triggers -Wunused-function warning (a.k.a. error) when building this
part of the code:
qpixellayout.cpp:292:25: error: unused function 'fetchPixel' [-Werror,-Wunused-function]
inline uint QT_FASTCALL fetchPixel<QPixelLayout::BPP64>(const uchar *src, int index)
                        ^
qpixellayout.cpp:300:25: error: unused function 'fetchPixel' [-Werror,-Wunused-function]
inline uint QT_FASTCALL fetchPixel<QPixelLayout::BPP16FPx4>(const uchar *src, int index)
                        ^
qpixellayout.cpp:308:25: error: unused function 'fetchPixel' [-Werror,-Wunused-function]
inline uint QT_FASTCALL fetchPixel<QPixelLayout::BPP32FPx4>(const uchar *src, int index)

Change-Id: I8ff40e3cf02f8a7ad7534f58ac23eeb8eb716d3a
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>