Fix build with -no-feature-buttongroup
.../qabstractbutton.cpp: In member function ‘virtual void
QAbstractButton::keyPressEvent(QKeyEvent*)’:
.../qabstractbutton.cpp:1010:58: error: incomplete type
‘QGuiApplicationPrivate’ used in nested name specifier

Change-Id: Ia71bb481d125087aa813c891f9508755f435f4d2
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit ca772a8ffa2fdde4238ff0af325997dd78dbfe83)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>