Work around GCC 6 warning about offset outside bounds of string
This is a false positive because the only offset that can be outside the
bounds was the last one (-1), which could not be reached in this line
because of the qBound on the line before limiting the maximum value.

The -1 wasn't generated by the Perl script embedded in the file anyway.

qdbuserror.cpp:142:64: error: offset outside bounds of constant string [-Werror]

Change-Id: I24a735698d3c4a719fc9ffff1425f8aad5e5978e
Reviewed-by: Alex Blasche <alexander.blasche@theqtcompany.com>
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@theqtcompany.com>