ohos: remove unused variable
src/plugins/styles/ohos/qohosstyle.cpp:1025:42: error: variable 'fropt' set but not used [-Werror,-Wunused-but-set-variable]
 1025 |         if (const QStyleOptionFocusRect *fropt = qstyleoption_cast<const QStyleOptionFocusRect *>(option)) {
      |                                          ^

Change-Id: I12ffe3dd4099f81dd77d43a391a579fd20d1c7a9
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>
Reviewed-by: Zbigniew Chyla <zbigniew.chyla@qt.io>
(cherry picked from commit 8ace529070261fd9b89cb69fd3f47b868d48bf9e)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>