Fix Clang 10 warning about LLONG_MAX being inexact in double
 validator.cpp:707:19: error: implicit conversion from 'long long' to 'double' changes value from
 9223372036854775807 to 9223372036854775808 [-Werror,- Wimplicit-int-float-conversion]

Task-number: QTBUG-83666
Change-Id: I99ab0f318b1c43b89888fffd160b4a95a258423b
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Samuel Gaist <samuel.gaist@idiap.ch>
(cherry picked from commit ff6d2cb0d5779d81e89d94d65c8d164602fa2567)