QArrayData: port from std::pair to a proper struct
Replace the std::pair-based ctor of QArrayDataPointer with a proper
struct. This is a cleaner API and has been recommended by the QtCore
maintainer for years.

This is SiC, but QArrayData is non-documented API, and we can
leave the exported function that returns std::pair alone, so it's BC.

Adapt some users, leave others in to test the deprecated conversion to
std::pair does what it's supposed to (decouple Qt module updates).
There's one user in qtdeclarative that needs an update. Will submit
under the same topic as this patch. By keeping the conversion to pair,
this patch and the qtdeclarative one can go in any order.

Pick to older branches as it just happens to fix a FTBFS in an odd
combination of older Clang with newer libstdc++, to wit:

C++23 added a std::pair(pair-like) ctor. For some contrived reason
older Clang with newer libstdc++ (tested: Clang 15 vs. GCC 15) are
buggy in this area. As far as I can make it out, in the QByteArray
defaulted move constructor, the compiler is looking for the
QArrayDataPointer move constructor. Before it settles on the obvious
candidate, though, it must build the overload set, and that contains
the

    QArrayDataPointer(std::pair<....>, qsizetype n = 0)

ctor. So the compiler duly tries whether other's QByteArray::d matches
said std::pair. And due to, apparently, a bug in the pair-like
constraint, or an incompatibility between the libstdc++ fomulation and
Clang's behavior, that causes a hard error instead of SFINAE'ing out.

Says Clang:

  bits/stl_pair.h:430:35: error: no matching function for call to 'get'
          return _S_convertible<decltype(std::get<0>(std::declval<_UPair>())),
                                         ^~~~~~~~~~~
  bits/stl_pair.h:544:22: note: in instantiation of function template specialization 'std::pair<QTypedArrayData<char> *, char *>::_S_convertible_from_pair_like<QArrayDataPointer<char>>' requested here
        constexpr explicit(!_S_convertible_from_pair_like<_UPair>())
                            ^
  qbytearray.h:101:12: note: while substituting deduced template arguments into function template 'pair' [with _UPair = QByteArray::DataPointer]
    inline QByteArray(QByteArray && other) noexcept
           ^
  qbytearray.h:190:20: note: in defaulted move constructor for 'QByteArray' first required here
            return std::move(*this);
                   ^
  [snip candidate listing]

A quick search didn't find any bug report about this, and since I
wanted to get rid of those std::pair for years already, anyway, and
this isn't a supported combination of Clang and libstdc++, I didn't
dig deeper.

Found while debugging QTBUG-145970.

Fixes: QTBUG-146013
Pick-to: 6.8
Change-Id: I30f34aa45a91975de9382d8c77b7819acc642a50
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit f1beeb305ac231cbb4bdd08ac3e77bc183922af8)
Reviewed-by: Ahmad Samir <a.samirh78@gmail.com>