QWidgetTextControl: Fix build with -no-feature-textodfwrite
.../qtbase/src/widgets/widgets/qwidgettextcontrol.cpp(3470): error C2059: syntax error: ')'

.../qtbase/src/widgets/widgets/qwidgettextcontrol.cpp(3478): error C3536: 'supportedMimeTypes': cannot be used before it is initialized

Drive-by change: apply the same fix for 'textmarkdownwriter' feature.

This amends commit 6cd8f1fbefba929427d694060fae7e4b26a73dee.

Change-Id: I78fd66c4d16003aa7e98b0f6b3dfcd1f9c5cb1e5
Reviewed-by: Ahmad Samir <a.samirh78@gmail.com>