Rename variable being shadowed
Otherwise building any application that includes this header while using -Werror=shadow fails with:

[   89s] /usr/include/qt6/QtCore/qtmochelpers.h:563:36:   in ‘constexpr’ expansion of ‘(& methods)->QtMocHelpers::UintData<QtMocHelpers::SignalData<void(libcamera::FrameBuffer*)> >::copyTo<{anonymous}::qt_meta_tag_ZN12ViewFinderGLE_t, QtMocHelpers::MetaObjectContents<24, 10, 60, 3> >(result, ((size_t)dataoffset), metatypeoffset)’
[   89s] /usr/include/qt6/QtCore/qtmochelpers.h:201:57: error: declaration of ‘entry’ shadows a member of ‘QtMocHelpers::detail::UintDataStorage<std::integer_sequence<int, 0>, QtMocHelpers::SignalData<void(libcamera::FrameBuffer*)> >’ [-Werror=shadow]
[   89s]   201 |         [[maybe_unused]] auto invoke = [&f](const auto &entry) { f(entry.entry); return 0; };
[   89s]       |                                             ~~~~~~~~~~~~^~~~~
[   89s] /usr/include/qt6/QtCore/qtmochelpers.h:180:7: note: shadowed declaration is here
[   89s]   180 |     T entry;
[   89s]       |       ^~~~~
[   89s] cc1plus: all warnings being treated as errors

Pick-to: 6.9
Change-Id: I7a3e48fc98acbfabf611b6be813b8576c7168499
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
(cherry picked from commit b843282a234efcae48ac0b494ab84028d94953c4)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>