QWinRegistry: Add missing include
qwinregistry.cpp(80): error C2079: 'list' uses undefined class 'qt::QList<qt::QString>'

Amends 40523b68c14bf618bdc2d5438deebf34627be3af

Change-Id: Ic622bed4ca3f3d270ab5f6a41f67151b0e40e359
Reviewed-by: Yuhang Zhao <2546789017@qq.com>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>