MinGW compile fix: Add missing inline keyword
Some compilers are picky about that the declaration needs to match the
definition also for the inline keyword:

qt5/qtbase/src/corelib/io/qfilesystemmetadata_p.h:239:27: error:
'QFileDevice::Permissions QFileSystemMetaData::permissions() const' redeclared
without dllimport attribute after being referenced with dll linkage [-Werror]
  239 | inline QFile::Permissions QFileSystemMetaData::permissions()...
      |                           ^~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors

Fix by declaring the function inline, not only at the definition.

Pick-to: 6.8
Change-Id: I68d1fd2f9952ec3bf54b1ba27461bf1751c9d301
Reviewed-by: Matthias Rauter <matthias.rauter@qt.io>