Fix build with Clang 3.8
Commit 128a6eec065dfe683e6d776183d63908ca02e8fb replaced the static,
unsorted list with a sorting implementation via templates.

qmakearray_p.h:109:8: fatal error: recursive template instantiation exceeded maximum depth of 256
qmakearray_p.h:111:39: note: during template argument deduction for  class template partial specialization 'QuickSortFilter<Predicate,
 QuickSortData<type-parameter-0-1, type-parameter-0-2...> >' [with Predicate = LessThan, Head = Xkb2Qt<269025163, 16777462>, Tail = ...]

Fixes: QTBUG-72579
Change-Id: I548dbfddb69b4fd6a0a3fffd15717ac2bf2d7361
Reviewed-by: Gatis Paeglis <gatis.paeglis@qt.io>
Reviewed-by: Mikhail Svetkin <mikhail.svetkin@qt.io>