Weak-import global objects used for logging on Apple platforms
Otherwise the dynamic loader will complain about missing symbols when
the binary is run on platforms below our supported deployment target:

dyld: Symbol not found: __os_activity_current
  Referenced from: QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/torarne/build/qt/5.12/qtbase/lib/QtCore.framework/Versions/5/QtCore
Trace/BPT trap: 5

We want this to trigger our own logic in qt_apple_check_os_version(),
where we tell the user in more friendly terms what's going on.

An alternative to the targeted weak imports would be do import the
whole library as weak, using  -weak-lSystem.B. This doesn't seem
to cause any performance issues at startup, but since we only need
the two global symbols we stick to the more targeted solution just
to be on the safe side.

Change-Id: I87c1f185f6dcf9df26c700d31bb5071ddf7685be
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>