Conan: Don't add 'qt_host_path' automatically when cross-building
We tried to "help" the user by passing the value from -o 'qt_host_path'
into CMake '-DQT_HOST_PATH=...' automatically. This involved updating
the 'cmake_args_qtbase' option by the recipe.

This did not work well with Conan lock files as the alteration of any
option caused:

  ERROR: qtbase/6.3.1@qt/everywhere: qtserialport/6.3.1@qt/everywhere
    tried to change qtbase/6.3.1@qt/everywhere option cmake_args_qtbase
    to '...' but it was already assigned to '...'.

Remove the part where the 'cmake_args_qtbase' value is being altered
but keep it where it is being utilized when aggregating the virtualenv
attributes.

Change-Id: Ib7fb1b7cf1b77ee4b5db5646d3be829bc3d1113f
Reviewed-by: Toni Saario <toni.saario@qt.io>
(cherry picked from commit 003538a4f3e6d427bc9d82e90ba3aa7789dce5c9)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>