QQuaternion: fix MingW "redeclared without dllimport attribute" error
I don't know why, but after years of no changes to the header, the CI
on 6.5 started to throw the dreaded

  qquaternion.h:138:8: error: 'QQuaternion::QQuaternion()' redeclared without dllimport attribute after being referenced with dll linkage [-Werror]

Fix by plastering the class with inline keywords. This just goes to
show that separating definition and declaration of inline functions
(and exporting non-polymorphic classes wholesale) is usually a bad
idea.

Remove the inline keywords from the definitions to order to use the
linker on all platforms to verify we marked all functions inline that
are.

Later releases are unaffected, because
f9f1272e7c438b79591032877f2b386af8085c3f plastered the class with
constexpr, which implies inline.

Manual conflict resolution for dev:

- there were three inline keywords left outside the class after
  f9f1272e7c438b79591032877f2b386af8085c3f, this patch removes them,
  so mark it as a cherry-pick of the 6.5 change, which did the same

Change-Id: I5f044e4aae8e31173c0717d4b70d53fece99b927
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit fccb455a4f94e5bc95ba6ad54a46fa71439314bb)
Reviewed-by: Daniel Smith <daniel.smith@qt.io>
(cherry picked from commit 1b1cb5bf666df76be876e593da04125f21c7b30b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit dea1706b7799ee1f659dee2c8a8282dd6fcbf8c1)
(cherry picked from commit ba0847ad338b7b19124c52359de0226b8c38a7de)