QToolBarExtension: remove unused member 'orientation'
The orientation is implicitly stored by which icon is used.

Found by Clang:
  qtoolbarextension_p.h:57:21: error: private field 'orientation' is not used [-Werror,-Wunused-private-field]

Change-Id: I82f8b8009b48d41fd2beb95d6107e505f9d4e835
Reviewed-by: Olivier Goffart (Woboq GmbH) <ogoffart@woboq.com>