QNX: add missing include
src/plugins/platforms/qnx/qqnxscreeneventhandler.cpp:149:42: error: incomplete type 'QTouchDevice' used in nested name specifier
     m_touchDevice->setType(QTouchDevice::TouchScreen);
                                          ^~~~~~~~~~~

Change-Id: I83fbecfb3b0745d2f8f30d946f3ee3bd5d6c7459
Reviewed-by: James McDonnell <jmcdonnell@blackberry.com>