QQuaternion: fix MingW "redeclared without dllimport attribute" error
I don't know why, but after years of no changes to the header, the CI
on 6.5 started to throw the dreaded

  qquaternion.h:138:8: error: 'QQuaternion::QQuaternion()' redeclared without dllimport attribute after being referenced with dll linkage [-Werror]

Fix by plastering the class with inline keywords. This just goes to
show that separating definition and declaration of inline functions
(and exporting non-polymorphic classes wholesale) is usually a bad
idea.

Remove the inline keywords from the definitions to order to use the
linker on all platforms to verify we marked all functions inline that
are.

Later releases are unaffected, because
f9f1272e7c438b79591032877f2b386af8085c3f plastered the class with
constexpr, which implies inline.

Change-Id: I5f044e4aae8e31173c0717d4b70d53fece99b927
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>