QtCore/MSVC: Fix unity build error
Exclude qassert.cpp, fixing:
error C2375: 'qAbort': redefinition; different linkage

Amends 23877db5639deca70dc8cc1a7299b2cee629c7d8.
Introduced by 907e9a8b293a0a4372ea474ad76e7507e7c7ebd9.

Change-Id: I03d6d31eda138a411d1972f683f46c0437f8d839
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 673605110e3a33db9b58e0c514e9ec8e4da36d20)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>