Fix build with -no-feature-egl
qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_egl/qxcbeglinclude.h:12:10: fatal error: QtGui/private/qt_egl_p.h: No such file or directory
   12 | #include <QtGui/private/qt_egl_p.h>

Change-Id: Ie243fc05e165524afebb10ec979b5f72de8681ce
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>
(cherry picked from commit c9df9f3976d969dc1f829a596016a377f1e619f4)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>