QDateTime: fix build with MinGW: need unistd.h very early
qobject.h has #include <chrono>, which #includes <ctime>, which includes
<time.h>.

datetime.cpp:2621:23: error: 'localtime_r' was not declared in this scope; did you mean 'localtime_s'?

Change-Id: I2bbf422288924c198645fffd16a922719c4ce7d4
Reviewed-by: Edward Welbourne <edward.welbourne@qt.io>
(cherry picked from commit 684c9b82b9b8216f406c59deb35cd727ffb6d69b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>