qwasmsuspendresumecontrol: Add missing include for QDebug
Amends 914ff198ad7cab26c9d38cf843a8c144026f83ba to
address this build error seen in a local wasm build:

    .../qtbase/src/corelib/platform/wasm/qwasmsuspendresumecontrol.cpp:158:9: error: calling 'warning' with incomplete return type 'QDebug'
      158 |         qWarning() << "QWasmSuspendResumeControl::~QWasmSuspendResumeControl - still remaining " << m_eventHandlers.size() << " handlers";
          |         ^~~~~~~~~~
    .../qtbase/src/corelib/global/qlogging.h:171:93: note: expanded from macro 'qWarning'
      171 | #define qWarning QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC).warning
          |                                                                                             ^
    .../qtbase/src/corelib/global/qlogging.h:121:12: note: 'warning' declared here
      121 |     QDebug warning() const;
          |            ^
    .../qtbase/src/corelib/global/qtypeinfo.h:16:7: note: forward declaration of 'QDebug'
       16 | class QDebug;
          |       ^
    .../qtbase/src/corelib/platform/wasm/qwasmsuspendresumecontrol.cpp:158:20: error: invalid operands to binary expression ('QDebug' and 'const char[73]')
      158 |         qWarning() << "QWasmSuspendResumeControl::~QWasmSuspendResumeControl - still remaining " << m_eventHandlers.size() << " handlers";
          |         ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Task-number: QTBUG-145008
Change-Id: Ie9de9f36161fa6adbfcde791dc7cfb14cdb0d070
Reviewed-by: Even Oscar Andersen <even.oscar.andersen@qt.io>
Reviewed-by: Morten Johan Sørvig <morten.sorvig@qt.io>
(cherry picked from commit 4ff2a3384658bb19f047f3b7b365e9180d75fc05)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>