convertDoubleTo: fix truncation warning with Clang 20
Amends df8456061ef0d57ea6be37746951c50f38a65101

qnumeric_p.h:251:63: error: implicit conversion from 'const long long' to 'double'
                     changes value from 9223372036854775807 to 9223372036854775808
                     [-Werror,-Wimplicit-const-int-float-conversion]

Change-Id: I2d8f7a38574a89185d30fffdb7bee086f2b23eee
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit 5815084ad2dcaed6bfd8eb9314a4ed8a7e4654ca)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 3575157919ccf4c4d2e2be7a68dc0021ef47a6f4)
(cherry picked from commit ec832175786f3075532c03fed68111a118d30afb)
(cherry picked from commit 434366d9e2e8f14ca95a09eb8996acf414295fb1)