Add newline after import
This avoids -Wnewline-eof for clang compilers.

error: no newline at end of file [-Werror,-Wnewline-eof]
    Q_IMPORT_PLUGIN(Governikus_AnimationsPlugin)

Change-Id: I8de21f1f27cd177211ebf70fac0e01292cfa410c
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>
(cherry picked from commit f926ccbf64791ded226da187674e7a5f6a40eca7)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 13590640c3d9a4b8088f19981f9cdf2c0a1a27a9)
(cherry picked from commit 368521adc8fc008524fa74fbe370fb774b173167)