ohos: remove unused variable
src/plugins/styles/ohos/qohosstyle.cpp:1025:42: error: variable 'fropt' set but not used [-Werror,-Wunused-but-set-variable]
 1025 |         if (const QStyleOptionFocusRect *fropt = qstyleoption_cast<const QStyleOptionFocusRect *>(option)) {
      |                                          ^

Pick-to: 6.12
Change-Id: I12ffe3dd4099f81dd77d43a391a579fd20d1c7a9
Reviewed-by: SanthoshKumar Selvaraj <santhosh.kumar.selvaraj@qt.io>
Reviewed-by: Zbigniew Chyla <zbigniew.chyla@qt.io>