QXdgDesktopPortalFileTransfer: fix build - missing #includes
Amends cd541ce332ce4b9901d776e860f0f6428f4be68a.

qxdgdesktopportalfiletransfer_p.h:24:27: error: expected constructor, destructor, or type conversion before ‘(’ token
   24 | Q_DECLARE_LOGGING_CATEGORY(lcQpaPortalFileTransfer);
qxdgdesktopportalfiletransfer.cpp:38:54: error: incomplete type ‘QDBusConnection’ used in nested name specifier
qxdgdesktopportalfiletransfer.cpp:45:27: error: ‘QFile’ has not been declared
qxdgdesktopportalfiletransfer.cpp:46:28: error: invalid use of incomplete type ‘class QDBusUnixFileDescriptor’
etc.

This isn't being tested in the CI.

Pick-to: 6.12
Change-Id: Iae7f25cfbebae5af9e11fffdd6f413363170f4d9
Reviewed-by: David Redondo <qt@david-redondo.de>