Fix uninitialized variable warning with gcc 4.9.0
Code is new in dev, introduced by e8892c7e7a0bdebca9ff491a9446c0b4192fe7fd

util/qsystemtrayicon.cpp: In member function 'void QSystemTrayIcon::showMessage(const QString&, const QString&, QSystemTrayIcon::MessageIcon, int)':
util/qsystemtrayicon.cpp:78:55: error: 'stdIcon' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     return QApplication::style()->standardIcon(stdIcon);

Change-Id: I6bdfffc60936ffd0f9baaa3019e701fab011e224
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>