ohos: avoid a complain about RasterGLSurface
src/plugins/platforms/ohos/qohosplatformintegration.cpp:252:13: error: enumeration value 'RasterGLSurface' not handled in switch [-Werror,-Wswitch]
  252 |     switch (window->surfaceType()) {
      |             ^~~~~~~~~~~~~~~~~~~~~

RasterGLSurface was deprecated in
8391c01f38c9101ab8e275354e82b489457a6bc6 (6.11), but this code was
added only for 6.12.

Pick-to: 6.12
Change-Id: I6668fb51f978ecb2b24981890461af074a72e0e8
Reviewed-by: Marc Mutz <marc.mutz@qt.io>