QQuaternion: comment all #endif's
It's easier to comprehend what's going on, because there are quite a
few different ones here.

Exception: if the #if block contains only very few lines (max four or
so, didn't count), then a naked #endif is ok, and arguably easier on
the eye, so leave them in that case.

Amends the start of the public history.

Change-Id: Ib1b27859344916caa17dc1ff0010b6b10d34bb13
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit d9e77680600de1bdcd8009c6a2cfdf82de2085fc)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 1cf2fffee41fdb00deb52e2f330a9fca10e95734)
(cherry picked from commit 595c9956d59a8a57b729efbb22d442787bccc4e9)
(cherry picked from commit dc791bf4d4af8acb4aadda3444bdb5c10600724d)
Reviewed-by: Marc Mutz <marc.mutz@qt.io>